// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | rgb565
//    output | generated
//    input  | animation.gif

#pragma once

#include <qp.h>

extern const uint32_t gfx_animation_length;
extern const uint8_t  gfx_animation[303987];
